### ISSUE TITLE
It keeps saying InvalidPassword

### ISSUE THREAD

**Issue by Deathzz007** [andrewda/node-steam-guide#44]
Error: InvalidPassword
    at SteamUser._handlers.(anonymous function) (/Users/wolfy/Desktop/Steambot/node_modules/steam-user/components/logon.js:363:16)
    at SteamUser._handleMessage (/Users/wolfy/Desktop/Steambot/node_modules/steam-user/components/messages.js:216:29)
    at emitThree (events.js:116:13)
    at CMClient.emit (events.js:194:7)
    at CMClient._netMsgReceived (/Users/wolfy/Desktop/Steambot/node_modules/steam-client/lib/cm_client.js:323:8)
    at CMClient.handlers.(anonymous function) (/Users/wolfy/Desktop/Steambot/node_modules/steam-client/lib/cm_client.js:603:8)
    at CMClient._netMsgReceived (/Users/wolfy/Desktop/Steambot/node_modules/steam-client/lib/cm_client.js:305:24)
    at emitOne (events.js:96:13)
    at TCPConnection.emit (events.js:188:7)
    at TCPConnection._readPacket (/Users/wolfy/Desktop/Steambot/node_modules/steam-client/lib/tcp_connection.js:179:7)

Its keeps saying when I code on chapter 1.4 and above. If its a bug please fix. If not, please help me whats going on thanks.

**Comment by AvoJFB** [comment]
Are you sure that your password is correct?

**Comment by xmwx38** [comment]
I had a similar problem with using [SteamBot](https://github.com/Jessecar96/SteamBot).  I know for a fact I added the password correct each time.  It turns out the problem was that no attempts to retrieve a SteamGuard code to complete login.  

I received errors which stated something like "error: invalid password,"

**Comment by Deathzz007** [comment]
Yes I have entered the password correctly and also I realized the code was the deal 
When I put this it works:
const logOnOptions = {
	accountName: 'username what I put in",
	password: 'password what I put in"
But it doesn't work when I put this:
       accountName: "username what I put in";
       password: "password what I put in",  
      TwoFactorCode: SteamTotp.generateAuthCode('your_steam_shared_secret')


I think its a bug or needs a update idk really but suggestions would be greatly appreciated

**Comment by andrewda** [comment]
You should be using `twoFactorCode`, not `TwoFactorCode`.
