### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by D3M3NTOS** [andrewda/node-steam-guide#67]
/home/bot/node_modules/steam-totp/index.js:28
                        let code = exports.generateAuthCode(secret, offset);
                        ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/bot/bot.js:5:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
root@csgowoob:/home/bot# /home/bot/node_modules/steam-totp/index.js:28
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/bot/bot.js:5:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by andrewda** [comment]
Upgrade to the newest version of Node.js.
