### ISSUE TITLE
4.4 Database.

### ISSUE THREAD

**Issue by DopplaCSGO** [andrewda/node-steam-guide#7]
Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html

Is what I'm getting on the 4.4 after trying to launch project6.js

could you explain how to set up the database as well? as on the tutorial it says nothing about how to create or view it in the first place.

Thanks

**Comment by DopplaCSGO** [comment]
C:\Users\Lewis\Downloads\Node\node_modules\mongoose\node_modules\mongodb\lib\server.js:265
        process.nextTick(function() { throw err; })
                                      ^
 MongoError: failed to connect to server [127.0.0.1:27017] on first connect
    at null.<anonymous> (C:\Users\Lewis\Downloads\Node\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\lib\topologies\server.js:325:35)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at null.<anonymous> (C:\Users\Lewis\Downloads\Node\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\lib\connection\pool.js:270:12)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at Socket.<anonymous> (C:\Users\Lewis\Downloads\Node\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\lib\connection\connection.js:173:49)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1269:8)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

are the errors if needed

**Comment by andrewda** [comment]
Hey there!

Make sure you have MongoDB installed and running. You can follow the tutorials [here](https://docs.mongodb.com/manual/installation/#tutorials) for your operating system to install MongoDB.

Also – your `mpromise` depreciation warning can be ignored because we will not be using Mongoose promises in this guide.

**Comment by DopplaCSGO** [comment]
Okay, got the database up, and added the items but when I connect to the site i now get this:

Error: Failed to lookup view "main" in views directory "C:\Users\Lewis\Downloads\Node\views"
   at EventEmitter.render (C:\Users\Lewis\Downloads\Node\node_modules\express\lib\application.js:579:17)
   at ServerResponse.render (C:\Users\Lewis\Downloads\Node\node_modules\express\lib\response.js:960:7)
   at C:\Users\Lewis\Downloads\Node\project7.js:23:7
   at Query.<anonymous> (C:\Users\Lewis\Downloads\Node\node_modules\mongoose\lib\model.js:3407:16)
   at C:\Users\Lewis\Downloads\Node\node_modules\mongoose\node_modules\kareem\index.js:259:21
   at C:\Users\Lewis\Downloads\Node\node_modules\mongoose\node_modules\kareem\index.js:127:16
   at nextTickCallbackWith0Args (node.js:420:9)
   at process._tickCallback (node.js:349:13)

I have the same setup as in your example

**Comment by DopplaCSGO** [comment]
C:\Users\Lewis\Downloads\Node>node project7.js
Error: Failed to lookup view "main" in views directory "C:\Users\Lewis\Downloads\Node\views"
    at EventEmitter.render (C:\Users\Lewis\Downloads\Node\node_modules\express\lib\application.js:579:17)
    at ServerResponse.render (C:\Users\Lewis\Downloads\Node\node_modules\express\lib\response.js:960:7)
    at C:\Users\Lewis\Downloads\Node\project7.js:23:7
    at Query.<anonymous> (C:\Users\Lewis\Downloads\Node\node_modules\mongoose\lib\model.js:3407:16)
    at C:\Users\Lewis\Downloads\Node\node_modules\mongoose\node_modules\kareem\index.js:259:21
    at C:\Users\Lewis\Downloads\Node\node_modules\mongoose\node_modules\kareem\index.js:127:16
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

is the cmd error

**Comment by andrewda** [comment]
If you're following the top part of Chapter 4.4 (i.e. creating database records) then your code should look like [this](https://github.com/andrewda/node-steam-guide/blob/master/Chapter%204%20-%20Basics%20of%20Web%20Development/Chapter%204.4%20-%20Using%20Databases/project6.js). If you're following the bottom part (incorporating the database into the website) then your code should look like [this](https://github.com/andrewda/node-steam-guide/tree/master/Chapter%204%20-%20Basics%20of%20Web%20Development/Chapter%204.4%20-%20Using%20Databases/project7).

It seems like you're trying to run code referencing `/views/main.hbs` without having that file.

**Comment by DopplaCSGO** [comment]
@andrewda Pledged to you on patreon, I've given you my idea :D
