### ISSUE TITLE
Error: Cannot find module 'steam-user'

### ISSUE THREAD

**Issue by SullFurix** [andrewda/node-steam-guide#88]
C:\Users\SullFurix\Desktop\bot\BOT-Steam>node bot.js
module.js:549
    throw err;
    ^

Error: Cannot find module 'steam-user'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\SullFurix\Desktop\bot\BOT-Steam\bot.js:1:81)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

You can help me ? ; )

**Comment by andrewda** [comment]
Run `npm install steam-user` (and `npm install` any other modules that are required, too)
