### ISSUE TITLE
Add chapter on chat messages #50 issue

### ISSUE THREAD

**Issue by kebaburmum** [andrewda/node-steam-guide#92]
When ill type the command take all, it first said that manager is not defined so I add this line const manager = require('steam-user'); but now it says this, any help?  
Chat From 76561198154182487: !take-all tf2
C:\Users\herni\Desktop\sandvich\Nová složka\project1.js:232
    manager.loadInventory(appid, contextid, true, (err, inventory) => {
                   ^

TypeError: manager.loadInventory is not a function
    at takeAll (C:\Users\herni\Desktop\sandvich\Nová složka\project1.js:232:13)
    at SteamUser.client.on (C:\Users\herni\Desktop\sandvich\Nová složka\project1.js:170:17)
    at SteamUser.emit (events.js:187:15)
    at SteamUser._emitIdEvent (C:\Users\herni\Desktop\sandvich\Nová složka\node_modules\steam-user\components\utility.js:29:12)
    at SteamUser._handlers.(anonymous function) (C:\Users\herni\Desktop\sandvich\Nová složka\node_modules\steam-user\components\chat.js:281:9)
    at SteamUser._handleMessage (C:\Users\herni\Desktop\sandvich\Nová složka\node_modules\steam-user\components\messages.js:249:30)
    at CMClient.emit (events.js:187:15)
    at CMClient._netMsgReceived (C:\Users\herni\Desktop\sandvich\Nová složka\node_modules\steam-client\lib\cm_client.js:323:8)
    at CMClient.handlers.(anonymous function) (C:\Users\herni\Desktop\sandvich\Nová složka\node_modules\steam-client\lib\cm_client.js:609:8)
    at CMClient._netMsgReceived (C:\Users\herni\Desktop\sandvich\Nová složka\node_modules\steam-client\lib\cm_client.js:305:24)

C:\Users\herni\Desktop\sandvich\Nová složka>pause
Press any key to continue . . .

**Comment by kebaburmum** [comment]
the arrow should go to the loadinventory sry

**Comment by kebaburmum** [comment]
Guys im having a problems. Could anyone post here the full code with this but without sending trade offers, handling them etc cuz I got another bot for that. If you post it thx so much
